apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - name: "8910"
    port: 8910
    targetPort: 8910
  selector:
    # app: reverseproxy
    # service: reverseproxy
    app: reverseproxy
    
